name: Deploy Site
on: [push]

jobs:
  build:
    name: Build Gatsby Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          docker login -u gcardona -p ${DOCKER_TOKEN}
          docker pull gcardona/blog-gatsby
          docker build --file Dockerfile -t gcardona/blog-gatsby .
          docker push gcardona/blog-gatsby
  deploy_content:
    name: Deploy Content
    needs: build
    container:
      image: gcardona/blog-gatsby
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_GATSBY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_GATSBY }}
      volumes:
        -  ${GITHUB_WORKSPACE}/my-blog/:/usr/src/app
    steps:
      - uses: actions/checkout@v1
      - name: Deploy
        run: |
          yarn build
          yarn deploy -y
        